rmax/scrapy-redis

- .gitignore
- README.rst
- scrapy_redis/spiders.py
Minor changes in order to use with scrapy 0.22
> Upgrading to scrapy 0.22

- .dockerignore
- .gitignore
- Dockerfile
- README.rst
- docker-compose.yml
Just some dockerizing and fast scaling.
> Using Docker for sample-project

- example-project/example/spiders/mycrawler_redis.py
- example-project/example/spiders/myspider_redis.py
Typo in the example project. Tested already.
> fix typo of allowed_domain

- src/scrapy_redis/spiders.py
Sometimes we need to build multiple request tasks based on a single keyword
> init batch tasks

- README.rst
- src/scrapy_redis/defaults.py
- src/scrapy_redis/stats.py
Based on this extension, all the stats can be shared based on Redis among all the spiders.
> Add stats extension based on Redis

- src/scrapy_redis/spiders.py
refer to #98 
Update from_crawler's first argument from self to cls, it should be more clear
> Update from_crawler's first argument

- CONTRIBUTING.rst
- Makefile
- pytest.ini
- tox.ini
> [IMPROVEMENT] Update pytest config and related doc

- src/scrapy_redis/spiders.py
> Update collections library before deprecated

- src/scrapy_redis/spiders.py
> Remove redundant self at line 79, 82, 89 from spiders.py

- src/scrapy_redis/defaults.py
- src/scrapy_redis/spiders.py
- tests/test_spiders.py
> Refactor max idle time

- .readthedocs.yml
> [Docs] Try fix the docs

- README.rst
- src/scrapy_redis/spiders.py
> Update support for json data

- src/scrapy_redis/spiders.py
- src/scrapy_redis/utils.py
> fix push json

- .flake8
- CONTRIBUTING.rst
- tests/test_picklecompat.py
- tests/test_spiders.py
Old version `flake8` guide in `CONTRIBUTING.rst` has some miss using.
Update `flake8` guide in `CONTRIBUTING.rst` and add latest `flake8` usage, config file, and fix style suggestion.
> [test] Dev flake8 style

- src/scrapy_redis/spiders.py
I think the default method should `GET` ,meta default `{}`
if the push data has no `url` should return  `IIterable`
> [dev] Default value for json support data

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Create templates for issues and PRs.
> [CI/CD] Create templates for issue & pull request

- TODO.rst
- tox.ini
Action `build` failed after resolve #252 conflict. Add `build` to tox.ini to fix the error.
Fixes #252 
- OS version: Ubuntu 21.04
> [CI/CD] Fix action build

- tox.ini
* Update `tox.ini` to support `python3.11`.
* Update and increase `scrapy`, `redis` test options, include the latest version.
Fixes #273
- OS version: Ubuntu 20.04
> [update] tox.ini

- requirements.txt
Cleanup unnecessary requirements, and move them to `requirements-test.txt`.
Fixes #268
- OS version: Ubuntu 20.04
> [dev] Cleanup requirements

- README.rst
Some status badges are expired. Remove requirement badge (expired) and update `CI` badge to `GitHub Action` badge.
> [DEV] Add GitHub Action badge

- .github/workflows/builds.yml
- .github/workflows/checks.yml
- .github/workflows/tests.yml
- README.rst
Rename workflow's name and add them to our `README.md` seperately.
> [dev] Update GitHub Badge

- src/scrapy_redis/spiders.py
- tests/test_spiders.py
[Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.](https://github.com/scrapy/scrapy/issues/5994)
Fixes #(issue)
- remove 'spider' argument to ExecutionEngine.crawl
> [spiders] Remove 'spider' argument to ExecutionEngine.crawl

- src/scrapy_redis/dupefilter.py
Removed the unused import for request_fingerprint. 
As this throws the warning when running.
> Removed unused import.

- .github/workflows/builds.yml
- .github/workflows/checks.yml
- .github/workflows/tests.yml
- requirements-tests.txt
- src/scrapy_redis/dupefilter.py
- src/scrapy_redis/spiders.py
- tox.ini
Use python 3.12 for builds.
CI
> build: use python3.12 as default version

- .bumpversion.cfg
- .github/workflows/docs.yml
- .gitignore
- .readthedocs.yml
- CONTRIBUTING.rst
- HISTORY.rst
- docs/conf.py
- docs/index.rst
- docs/modules.rst
- src/scrapy_redis/spiders.py
- tox.ini
> docs: fix readthedocs
