scrapy_redis/spiders.py

`set_crawler` is not executed anymore when a spider is created

Make a RedisSpider compatible with a new version of scrapy

---

.travis.yml
README.rst
example-project/example/items.py
example-project/example/spiders/dmoz.py
example-project/example/spiders/mycrawler_redis.py
example-project/example/spiders/myspider_redis.py
scrapy_redis/dupefilter.py
scrapy_redis/pipelines.py
scrapy_redis/scheduler.py
scrapy_redis/spiders.py
scrapy_redis/tests.py
setup.py

This changes makes `scrapy-redis` compatible only with Scrapy 1.0.

Release 0.6.0

---

scrapy_redis/spiders.py

In my use case, I queue up URLs based on user activity, not crawling. Pushing into a list causes a tons of duplications, this allows me to change the behavior to use a SET without breaking existing behavior.

SET support

---

src/scrapy_redis/spiders.py

This avoids this error when running the redis spider:
```shell
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
msg = self.format(record)
File "/usr/lib/python3.5/logging/__init__.py", line 830, in
format
return fmt.format(record)
File "/usr/lib/python3.5/logging/__init__.py", line 567, in
format
record.message = record.getMessage()
File "/usr/lib/python3.5/logging/__init__.py", line 330, in
getMessage
msg = msg % self.args
ValueError: incomplete format
```
more traceback:
```shell
Message: "Reading start URLs from redis key '%(redis_key)s' (batch size:
%(redis_batch_size)s, encoding: %(redis_encoding)"
Arguments: {'redis_encoding': 'utf-8', 'redis_batch_size': 16,
'crawler': <scrapy.crawler.Crawler object at …
```

fixed formatting of logging command

---

src/scrapy_redis/dupefilter.py
src/scrapy_redis/scheduler.py

redis dupefilter is based on spider, it may suppport from spider.

make dupefilter support create from spider

---

example-project/example/spiders/dmoz.py

It seems dmoz.org is nolonger alive. It has been replaced by dmoz-odp.org.

fix(example): update dmoz spider domain

---

src/scrapy_redis/spiders.py

Speed up the read task using the redis pipeline

use pipeline when read redis list queue

---

src/scrapy_redis/connection.py

In redis-py on python 3 we have the option to construct our redis class with the kwarg
`decode_responses=True` which will decode bytes received from redis requests to python 3 strings ('utf-8')
This is really useful behavior because without it we have to decode all bytes before we use them, (not hard but tedious). 
This PR adds a setting to enable that behavior in python versions > (3,)

Add option to decode responses in python3

---

README.rst
src/scrapy_redis/spiders.py

新增空闲最大等待时间MAX_IDLE_TIME_BEFORE_CLOSE.
在设置中使用MAX_IDLE_TIME_BEFORE_CLOSE来表示最大的等待秒数.
不设置或为0时，则会一直等待.
MAX_IDLE_TIME_BEFORE_CLOSE不会影响SCHEDULER_IDLE_BEFORE_CLOSE的使用.
----------------------------
Added maximum idle waiting time MAX_IDLE_TIME_BEFORE_CLOSE.
Use MAX_IDLE_TIME_BEFORE_CLOSE in the settings to indicate the maximum number of seconds to wait.
If it is not set or 0, it will wait forever.
MAX_IDLE_TIME_BEFORE_CLOSE will not affect the use of SCHEDULER_IDLE_BEFORE_CLOSE.

Added maximum idle waiting time MAX_IDLE_TIME_BEFORE_CLOSE.

---

README.rst
requirements-install.txt

In redis-py < 3.0, `redis.Redis.spop()` takes only two arguments which are `self` and `name`. But `self.fetch_data(self.redis_key, self.redis_batch_size)` applies `self` and two other arguments to self.fetch_data which is `redis.Redis.spop()` indeed. This could cause an error `TypeError: spop() takes 2 positional arguments but 3 were given`

doc: fix redis-py dependency version

---

src/scrapy_redis/stats.py

Return the stats_key correctly if `spider` is passed in `._get_key(spider)`.

Fix RedisStatsCollector._get_key()

---

example-project/example/pipelines.py
example-project/example/settings.py

refer to #207
Update current files to pass flake8 check.

Flake8 update for files.

---

.gitignore
LICENSE
README.rst

Update .gitignore & LICENSE 

---

CONTRIBUTING.rst
README.rst
docs/installation.rst

fix #226 
The code lines in docs currently has the `$` prefix, which makes GitHub copy utility can't work as expected.
Remove the `$` prefix from all docs.

[docs] Remove docs $ prefix

---

Makefile

fix #226 
`Makefile` hasn't update for a long while, needs to check whether works functionally as expected or not and removes `python 2.x` support.
* Check each command works functionally or not.
* Remove `python 2.x` support and add a warning message.

Remove python 2.x support

---

src/scrapy_redis/spiders.py

An error `scrapy_redis has no module TextColor` occurred when perform `tox` test
Change `from scrapy_redis import TextColor` to `from scrapy_redis.utils import TextColor` in spiders.py

Update import scrapy_redis.utils

---

src/scrapy_redis/queue.py
src/scrapy_redis/utils.py
tox.ini

`scrapy-redis` relies on `python`, `scrapy`, `redis` work with each other, so there's a lot of combination to test
Use `tox` with `matrix` testing `python`, `scrapy`, `redis`'s combinations.

Dev tox matrix

---

docs/conf.py
src/scrapy_redis/queue.py
src/scrapy_redis/scheduler.py
src/scrapy_redis/spiders.py
tests/test_picklecompat.py
tests/test_scrapy_redis.py
tests/test_spiders.py

Convert string to fstring format, to follow `pylint` rules.
upstream PR #247 
fix #245 
For example
```python
raise ValueError("Failed to instantiate queue class '%s': %s", self.queue_cls, e)
raise ValueError(f"Failed to instantiate queue class '{self.queue_cls}':  {e}")
```

[style] Fix pylint style

---

src/scrapy_redis/defaults.py
src/scrapy_redis/spiders.py
tox.ini

Deprecate `REDIS_START_URLS_BATCH_SIZE` since there's no use case.
- OS version: Ubuntu 21.04

[settings] Deprecate REDIS_START_URLS_BATCH_SIZE

---

src/scrapy_redis/spiders.py
tox.ini

When a spider get parameter from settings, there's a duplicate type checking show as follow.
```python
if self.redis_batch_size is None:
self.redis_batch_size = settings.getint('CONCURRENT_REQUESTS', defaults.REDIS_CONCURRENT_REQUESTS)
try:
self.redis_batch_size = int(self.redis_batch_size)
except (TypeError, ValueError):
raise ValueError("redis_batch_size must be an integer")
```
Fixes #260 
- OS version: Ubuntu 21.04

[spiders] Remove duplicate check setting types

---

requirements.txt

There are 1 security vulnerabilities found in scrapy 2.0
- [CVE-2022-0577](https://www.oscs1024.com/hd/CVE-2022-0577)
Upgrade scrapy from 2.0 to 2.6.0 for vulnerability fix
Ideally, no insecure libs should be used.

fix(sec): upgrade scrapy to 2.6.0

---

src/scrapy_redis/dupefilter.py
tests/test_dupefilter.py

> scrapy offical recommend use `crawler.request_fingerprinter.fingerprint()` or `scrapy.utils.request.fingerprint()` to replace `scrapy.utils.request.request_fingerprint()`.
`scrapy.utils.request.request_fingerprint()` is about to deprecated.
Fixes #272
- OS version: Ubuntu 20.04

[dev] Deprecated function scrapy.utils.request.request_fingerprint() warning

---

src/scrapy_redis/dupefilter.py
tests/test_dupefilter.py

`request_fingerprint` is deprecated in `Scrapy`, but new `fingerprint` function requires a lot of changes of our code. Thus we need a customize `fingerprint` implementation for our own.
`Unittests` are also implemented, there are three new `unittests`
* `test_request_seen` with
* `same_request`
* `diff_method`
* `diff_url`
Fixes #272 
- OS version: Windows10 & WSL

[dev] Add customize fingerprint
